export const rootVariables = {
  zIndex: 'zindex',
  shadow: 'shadow',
  white: 'color-white',
  black: 'color-black',
  grey: 'color-grey',
  purple: 'color-purple',
  gradient: 'color-gradient',
  grey_light: 'color-grey-light',
  red_dark: 'color-red-dark',
  red_base: 'color-red-base',
  red_light: 'color-red-light',
  yellow_dark: 'color-yellow-dark',
  yellow_base: 'color-yellow-base',
  yellow_light: 'color-yellow-light',
  blue_dark: 'color-blue-dark',
  blue_base: 'color-blue-base',
  blue_light: 'color-blue-light',
  green_dark: 'color-green-dark',
  green_base: 'color-green-base',
  green_light: 'color-green-light',
};
